[project]
name = "backend"
version = "0.4.1"
description = "Main backend for web and data APIs of the Astro BEAM project"
readme = "README.md"
authors = [
    { name = "Hercules Konsoulas", email = "dyka3773@gmail.com" }
]
requires-python = "==3.13.*"
dependencies = [
    "aiokafka==0.13.0",
    "aiosmtplib==5.1.0",
    "asyncpg==0.31.0",
    "fastapi==0.128.0",
    "pydantic[email]==2.12.5",
    "pydantic-settings==2.12.0",
    "python-dotenv==1.2.1",
    "sqlalchemy==2.0.46",
    "uvicorn==0.40.0",
    "uvloop==0.22.1 ; sys_platform != 'win32'",
    "sqlmodel==0.0.31",
]

[project.scripts]
backend = "backend.main:main"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "python-semantic-release>=10.5.2",
    "tox==4.34.1",
]

[tool.semantic_release]
# build_command = "pip install build && python -m build" # Old build command
build_command = """
    python -m pip install uv
    uv lock --upgrade-package backend
    git add uv.lock
    uv build
""" # New build command with uv lock upgrade
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
tag_format = "v{version}"
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
exclude_commit_patterns = []
mode = "update"
insertion_flag = "<!-- insertion marker -->"
template_dir = "templates" # That means we should avoid creating such a folder unless we have custom changelog templates

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"
mask_initial_release = false

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf", "deps"]
allowed_tags = ["feat", "fix", "perf", "build", "chore", "ci", "docs", "style", "refactor", "test", "deps"]
parse_squash_commits = true
ignore_merge_commits = true

[tool.tox]
env_list = ["lint"] # Add more environments when needed

# Uncomment the following section to enable test environment
# [tool.tox.env_run_base]
# description = "Run tests with the current Python version"
# deps = [
#     "pytest>=8.4.2",
# ]
# commands = [[ "pytest", "-v" ]]

[tool.tox.envs.lint]
description = "Lint the codebase with ruff"
deps = [
    "ruff>=0.12.3",
]
skip_install = true
commands = [[ "ruff", "check", "src/", "tests/" ]]
